### ISSUE TITLE
Support for dicts

### ISSUE THREAD

**Issue by mvdpoel** [Gallore/yaml_cli#1]
Hi,

Nice tool! Only thing i'm missing is an option to set dicts:

```
env_variables:
  ENVIRONMENT: 'production'
  DB_HOST: 'host.tld'
  DB_USER: 'admin'
```

yaml_cli -f file.yaml --dict-append env_variables: DB_PASS: 'secret' DB_NAME: 'app_db'

which should result in:

```
env_variables:
  ENVIRONMENT: 'production'
  DB_HOST: 'host.tld'
  DB_USER: 'admin'
  DB_PASS: 'secret'
  DB_NAME: 'app_db'
```
